import Anthropic from '@anthropic-ai/sdk'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { sendLarkMessage } from '@/lib/lark'

const aiClient = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
const LEE_OPEN_ID = process.env.LEE_LARK_CHAT_ID ?? ''

const CLUSTER_HEADER_COLORS: Record<string, string> = {
  C1: 'indigo', C2: 'blue', C3: 'turquoise', C4: 'red', C5: 'green',
  C6: 'orange', C7: 'violet', C8: 'purple', C9: 'carmine', C10: 'wathet', C11: 'green',
}

const CLUSTER_NAMES: Record<string, string> = {
  C1: 'Johor Bahru', C2: 'Penang', C3: 'Nilai', C4: 'Ampang', C5: 'Ara Damansara',
  C6: 'PJ Subang', C7: 'Seri Kembangan', C8: 'Sentul', C9: 'Cheras',
  C10: 'Mont Kiara', C11: 'M Vertica',
}

export async function generateOCCCard(cluster: string, chatId: string): Promise<{ cardJson: Record<string, unknown>; textSummary: string }> {
  const today = new Date().toISOString().split('T')[0]

  const [session, clusterMsgs, incidents] = await Promise.all([
    supabaseAdmin.from('standup_sessions').select('*').eq('session_date', today).eq('cluster', cluster).single(),
    supabaseAdmin.from('lark_group_messages').select('sender_name, content').eq('cluster', cluster).gte('created_at', new Date(Date.now() - 14 * 3600000).toISOString()).limit(20),
    supabaseAdmin.from('incidents').select('title, status, severity').eq('cluster', cluster).not('status', 'eq', 'archived').limit(10),
  ])

  const commitments = session.data?.report_extracted ? JSON.stringify(session.data.report_extracted) : 'No standup report submitted'
  const activity = (clusterMsgs.data ?? []).map(m => `${m.sender_name}: ${m.content?.slice(0, 60)}`).join('\n')
  const openIncidents = (incidents.data ?? []).map(i => `${i.severity} ${i.title} (${i.status})`).join('\n')

  const msg = await aiClient.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 800,
    system: `Generate OCC nightly review for BeLive ${cluster} (${CLUSTER_NAMES[cluster]}). 50/50 rule: FIRST HALF praise specific behaviors (name person, name behavior, reference evidence). SECOND HALF question gaps with root cause thinking (question system not individual). Vary structure. Never template-like. Manglish, Lee's voice. Under 300 words.`,
    messages: [{ role: 'user', content: `Morning commitments:\n${commitments}\n\nToday's activity:\n${activity}\n\nOpen incidents:\n${openIncidents || 'None'}` }],
  })

  const occText = msg.content[0].type === 'text' ? msg.content[0].text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/i, '').trim() : ''

  const dateStr = new Date().toLocaleDateString('en-MY', { weekday: 'long', day: 'numeric', month: 'short' })

  const cardJson = {
    config: { wide_screen_mode: true },
    header: {
      template: CLUSTER_HEADER_COLORS[cluster] ?? 'blue',
      title: { tag: 'plain_text', content: `🌙 ${cluster} — ${CLUSTER_NAMES[cluster]} | OCC Nightly Review` },
    },
    elements: [
      { tag: 'markdown', content: occText },
      { tag: 'hr' },
      { tag: 'note', elements: [{ tag: 'plain_text', content: `Generated by Nucleus · ${new Date().toLocaleTimeString('en-MY')}` }] },
    ],
  }

  return { cardJson, textSummary: occText }
}

export async function sendEveningOCCs(targetClusters?: string[], testChatId?: string): Promise<Record<string, { sent: boolean }>> {
  const results: Record<string, { sent: boolean }> = {}
  const today = new Date().toISOString().split('T')[0]

  let clusters: { cluster: string; chat_id: string }[] = []
  if (targetClusters) {
    const { data } = await supabaseAdmin.from('cluster_health_cache').select('cluster, chat_id').in('cluster', targetClusters)
    clusters = data ?? []
  } else {
    const { data } = await supabaseAdmin.from('cluster_health_cache').select('cluster, chat_id')
    clusters = data ?? []
  }

  for (const { cluster, chat_id } of clusters) {
    try {
      const { getLarkToken, getSafeChatId } = await import('@/lib/lark')
      const sendTo = getSafeChatId(testChatId ?? chat_id, 'chat_id')
      const { cardJson, textSummary } = await generateOCCCard(cluster, sendTo)

      // Try user token first (sends as Lee), fall back to bot
      let resData: Record<string, unknown> = {}
      const cardContent = JSON.stringify(cardJson)

      try {
        const { getLeeUserToken } = await import('@/lib/lark-tokens')
        const userToken = await getLeeUserToken()
        const userRes = await fetch('https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id', {
          method: 'POST',
          headers: { Authorization: `Bearer ${userToken}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ receive_id: sendTo, msg_type: 'interactive', content: cardContent }),
        })
        resData = await userRes.json()
        if (resData.code === 0) console.log(`[occ:${cluster}]`, 'Sent as Lee')
      } catch { /* fall back */ }

      if (resData.code !== 0) {
        const botToken = await getLarkToken()
        const botRes = await fetch('https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id', {
          method: 'POST',
          headers: { Authorization: `Bearer ${botToken}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ receive_id: sendTo, msg_type: 'interactive', content: cardContent }),
        })
        resData = await botRes.json()
      }
      const sent = resData.code === 0

      await supabaseAdmin.from('standup_sessions').upsert({
        session_date: today, cluster, chat_id: sendTo,
        occ_sent: sent, occ_sent_at: sent ? new Date().toISOString() : null,
        occ_card_json: cardJson, occ_lark_message_id: (resData as Record<string, Record<string, string>>).data?.message_id,
      }, { onConflict: 'session_date,cluster' })

      await supabaseAdmin.from('daily_messages').insert({
        cluster, session_date: today, message_type: 'evening_occ',
        direction: 'outbound', content_text: textSummary,
        content_card_json: cardJson, sender_name: 'Nucleus',
        lark_message_id: (resData as Record<string, Record<string, string>>).data?.message_id, sent_at: new Date().toISOString(),
      })

      await supabaseAdmin.from('cluster_health_cache').update({ occ_sent_today: true }).eq('cluster', cluster)

      results[cluster] = { sent }
    } catch (error) {
      console.error(`[occ:${cluster}]`, error instanceof Error ? error.message : 'Unknown')
      results[cluster] = { sent: false }
    }
  }

  return results
}
