import Anthropic from '@anthropic-ai/sdk'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { sendLarkMessage } from '@/lib/lark'

const aiClient = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
const LEE_OPEN_ID = process.env.LEE_LARK_CHAT_ID ?? ''

const CLUSTER_HEADER_COLORS: Record<string, string> = {
  C1: 'indigo', C2: 'blue', C3: 'turquoise', C4: 'red', C5: 'green',
  C6: 'orange', C7: 'violet', C8: 'purple', C9: 'carmine', C10: 'wathet', C11: 'green',
}

const CLUSTER_NAMES: Record<string, string> = {
  C1: 'Johor Bahru', C2: 'Penang', C3: 'Nilai', C4: 'Ampang', C5: 'Ara Damansara',
  C6: 'PJ Subang', C7: 'Seri Kembangan', C8: 'Sentul', C9: 'Cheras',
  C10: 'Mont Kiara', C11: 'M Vertica',
}

const IOE_MAP: Record<string, string> = {
  C1: 'Nureen', C2: 'Intan', C3: 'Aireen', C4: 'Aliya', C5: 'Aliya',
  C6: 'Intan', C7: 'Mardhiah', C8: 'Mardhiah', C9: 'Intan', C10: 'Nureen', C11: 'Airen',
}

export async function generateClusterBrief(cluster: string, chatId: string): Promise<{ cardJson: Record<string, unknown>; textSummary: string }> {
  // Gather data in parallel
  const [tickets, clusterMsgs, ooeGrpMsgs] = await Promise.all([
    supabaseAdmin.from('ai_report_tickets').select('*').eq('cluster', cluster).eq('status', 'open').order('age_days', { ascending: false }).limit(20),
    supabaseAdmin.from('lark_group_messages').select('sender_name, content').eq('cluster', cluster).gte('created_at', new Date(Date.now() - 24 * 3600000).toISOString()).order('message_time', { ascending: false }).limit(20),
    supabaseAdmin.from('lark_group_messages').select('sender_name, content').eq('cluster', 'ALL').gte('created_at', new Date(Date.now() - 24 * 3600000).toISOString()).limit(10),
  ])

  const ticketData = tickets.data ?? []
  const maintCount = ticketData.filter(t => !t.issue_description?.toLowerCase().includes('move')).length
  const overdueCount = ticketData.filter(t => t.sla_overdue).length
  const overnightSummary = (clusterMsgs.data ?? []).slice(0, 5).map(m => `${m.sender_name}: ${m.content?.slice(0, 80)}`).join('\n')

  // Generate AI brief
  const msg = await aiClient.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 800,
    system: `Generate a pre-standup brief for BeLive Property Hub cluster ${cluster} (${CLUSTER_NAMES[cluster]}). IOE: ${IOE_MAP[cluster]}. Lee Seng Hee style: direct, caring, Manglish. Include: ticket summary, overnight highlights, urgent items (max 5), AI insight. Under 300 words. Plain text sections separated by headers.`,
    messages: [{ role: 'user', content: `Tickets (${ticketData.length} open, ${overdueCount} overdue):\n${ticketData.slice(0, 5).map(t => `${t.ticket_id} ${t.unit_number} ${t.issue_description} ${t.age_days}d ${t.sla_overdue ? 'OVERDUE' : ''}`).join('\n')}\n\nOvernight:\n${overnightSummary || 'No overnight messages'}` }],
  })

  const briefText = msg.content[0].type === 'text' ? msg.content[0].text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/i, '').trim() : ''

  const today = new Date().toLocaleDateString('en-MY', { weekday: 'long', day: 'numeric', month: 'short', year: 'numeric' })

  // Build Lark v7 card
  const cardJson = {
    config: { wide_screen_mode: true },
    header: {
      template: CLUSTER_HEADER_COLORS[cluster] ?? 'blue',
      title: { tag: 'plain_text', content: `📊 ${cluster} — ${CLUSTER_NAMES[cluster]} | Pre-Standup Brief` },
    },
    elements: [
      { tag: 'markdown', content: `${today} · IOE: ${IOE_MAP[cluster]} · **${ticketData.length}** tickets · **${overdueCount}** overdue` },
      { tag: 'hr' },
      { tag: 'markdown', content: briefText },
      { tag: 'hr' },
      { tag: 'note', elements: [{ tag: 'plain_text', content: `Generated by Nucleus · ${new Date().toLocaleTimeString('en-MY')}` }] },
    ],
  }

  return { cardJson, textSummary: briefText }
}

export async function sendMorningBriefs(targetClusters?: string[], testChatId?: string): Promise<Record<string, { sent: boolean }>> {
  const results: Record<string, { sent: boolean }> = {}

  // Get clusters to brief
  let clusters: { cluster: string; chat_id: string }[] = []
  if (targetClusters) {
    const { data } = await supabaseAdmin.from('cluster_health_cache').select('cluster, chat_id').in('cluster', targetClusters)
    clusters = data ?? []
  } else {
    const { data } = await supabaseAdmin.from('cluster_health_cache').select('cluster, chat_id')
    clusters = data ?? []
  }

  const today = new Date().toISOString().split('T')[0]

  for (const { cluster, chat_id } of clusters) {
    try {
      const { getLarkToken, getSafeChatId } = await import('@/lib/lark')
      const sendTo = getSafeChatId(testChatId ?? chat_id, 'chat_id')
      const { cardJson, textSummary } = await generateClusterBrief(cluster, sendTo)

      // Send as interactive card via Lark API
      const token = await getLarkToken()
      const res = await fetch('https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id', {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ receive_id: sendTo, msg_type: 'interactive', content: JSON.stringify(cardJson) }),
      })
      const resData = await res.json()
      const sent = resData.code === 0
      const messageId = resData.data?.message_id ?? null

      // Upsert standup session
      await supabaseAdmin.from('standup_sessions').upsert({
        session_date: today, cluster, chat_id: sendTo,
        brief_sent: sent, brief_sent_at: sent ? new Date().toISOString() : null,
        brief_card_json: cardJson, brief_lark_message_id: messageId,
      }, { onConflict: 'session_date,cluster' })

      // Insert daily message
      await supabaseAdmin.from('daily_messages').insert({
        cluster, session_date: today, message_type: 'pre_standup',
        direction: 'outbound', content_text: textSummary,
        content_card_json: cardJson, sender_name: 'Nucleus',
        lark_message_id: messageId, sent_at: new Date().toISOString(),
      })

      // Update cluster health
      await supabaseAdmin.from('cluster_health_cache').update({ brief_sent_today: true }).eq('cluster', cluster)

      results[cluster] = { sent }
      console.log(`[brief:${cluster}]`, sent ? 'Sent' : `Failed: ${resData.msg}`)
    } catch (error) {
      console.error(`[brief:${cluster}]`, error instanceof Error ? error.message : 'Unknown')
      results[cluster] = { sent: false }
    }
  }

  // DM Lee summary
  if (LEE_OPEN_ID && !testChatId) {
    const sentCount = Object.values(results).filter(r => r.sent).length
    sendLarkMessage(LEE_OPEN_ID, `✅ Pre-standup briefs sent: ${sentCount}/11 clusters\n\nView: https://belive-nucleus.vercel.app/clusters`, 'open_id').catch(console.error)
  }

  return results
}
